version: 2

builds:
  - id: carapace-ffmpeg
    main: ./cmd/carapace-ffmpeg
    binary: carapace-ffmpeg
    ldflags:
      - -s -w
  - id: carapace-ffmpeg-debug
    main: ./cmd/carapace-ffmpeg-debug
    binary: carapace-ffmpeg-debug
    ldflags:
      - -s -w

archives:
  - id: carapace-ffmpeg
    builds:
      - carapace-ffmpeg
      - carapace-ffmpeg-debug
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: carapace-sh
    name: carapace-ffmpeg
