package argstream

// buildFFplayOptionIndex returns the option index for ffplay.
func buildFFplayOptionIndex() map[string]*OptionDef {
	options := []*OptionDef{
		// Global options (shared with ffmpeg)
		{CanonicalName: "L", ShortName: "L", Aliases: []string{"license"}, Description: "show license", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "h", ShortName: "h", Aliases: []string{"help", "?"}, Description: "show help", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueString},
		{CanonicalName: "version", ShortName: "version", Description: "show version", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "buildconf", ShortName: "buildconf", Description: "show build configuration", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "formats", ShortName: "formats", Description: "show available formats", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "demuxers", ShortName: "demuxers", Description: "show available demuxers", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "muxers", ShortName: "muxers", Description: "show available muxers", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "devices", ShortName: "devices", Description: "show available devices", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "codecs", ShortName: "codecs", Description: "show available codecs", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "decoders", ShortName: "decoders", Description: "show available decoders", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "encoders", ShortName: "encoders", Description: "show available encoders", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "bsfs", ShortName: "bsfs", Description: "show available bitstream filters", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "protocols", ShortName: "protocols", Description: "show available protocols", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "filters", ShortName: "filters", Description: "show available filters", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "pix_fmts", ShortName: "pix_fmts", Description: "show available pixel formats", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "sample_fmts", ShortName: "sample_fmts", Description: "show available sample formats", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "layouts", ShortName: "layouts", Description: "show channel layouts", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "dispositions", ShortName: "dispositions", Description: "show stream dispositions", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "colors", ShortName: "colors", Description: "show recognized color names", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "sources", ShortName: "sources", Description: "list sources of the input device", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueDevice},
		{CanonicalName: "sinks", ShortName: "sinks", Description: "list sinks of the output device", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueDevice},
		{CanonicalName: "loglevel", ShortName: "v", Description: "set logging level", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueLogLevel},
		{CanonicalName: "report", ShortName: "report", Description: "generate a report", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "hide_banner", ShortName: "hide_banner", Description: "suppress startup banner", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueBoolean},
		{CanonicalName: "cpuflags", ShortName: "cpuflags", Description: "force specific CPU flags", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueString},
		{CanonicalName: "cpucount", ShortName: "cpucount", Description: "force specific CPU count", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueInt},
		{CanonicalName: "max_alloc", ShortName: "max_alloc", Description: "set maximum memory allocation", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueInt},

		// Main options (ffplay-specific)
		{CanonicalName: "x", ShortName: "x", Description: "force displayed width", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueInt},
		{CanonicalName: "y", ShortName: "y", Description: "force displayed height", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueInt},
		{CanonicalName: "fs", ShortName: "fs", Description: "start in fullscreen mode", Scope: ScopePerFileOpt, Type: TypeBoolean},
		{CanonicalName: "an", ShortName: "an", Description: "disable audio", Scope: ScopePerStreamOpt, Type: TypeBoolean},
		{CanonicalName: "vn", ShortName: "vn", Description: "disable video", Scope: ScopePerStreamOpt, Type: TypeBoolean},
		{CanonicalName: "sn", ShortName: "sn", Description: "disable subtitles", Scope: ScopePerStreamOpt, Type: TypeBoolean},
		{CanonicalName: "ss", ShortName: "ss", Description: "seek to position", Scope: ScopeInputOnlyOpt, Type: TypeValue, ValueType: ValueDuration},
		{CanonicalName: "t", ShortName: "t", Description: "play only duration seconds", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueDuration},
		{CanonicalName: "bytes", ShortName: "bytes", Description: "seek by bytes", Scope: ScopePerFileOpt, Type: TypeBoolean},
		{CanonicalName: "seek_interval", ShortName: "seek_interval", Description: "custom seek interval in seconds", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueFloat},
		{CanonicalName: "nodisp", ShortName: "nodisp", Description: "disable graphical display", Scope: ScopePerFileOpt, Type: TypeBoolean},
		{CanonicalName: "noborder", ShortName: "noborder", Description: "borderless window", Scope: ScopePerFileOpt, Type: TypeBoolean},
		{CanonicalName: "alwaysontop", ShortName: "alwaysontop", Description: "window always on top", Scope: ScopePerFileOpt, Type: TypeBoolean},
		{CanonicalName: "volume", ShortName: "volume", Description: "startup volume (0-100)", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueInt},
		{CanonicalName: "f", ShortName: "f", Description: "force format", Scope: ScopeInputOnlyOpt, Type: TypeValue, ValueType: ValueFormat},
		{CanonicalName: "window_title", ShortName: "window_title", Description: "set window title", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueString},
		{CanonicalName: "left", ShortName: "left", Description: "window x position", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueInt},
		{CanonicalName: "top", ShortName: "top", Description: "window y position", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueInt},
		{CanonicalName: "loop", ShortName: "loop", Description: "loop count (0 = forever)", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueInt},
		{CanonicalName: "showmode", ShortName: "showmode", Description: "display mode: 0/video, 1/waves, 2/rdft", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueShowMode},
		{CanonicalName: "vf", ShortName: "vf", Description: "video filtergraph", Scope: ScopePerStreamOpt, Type: TypeValue, ValueType: ValueFilter, ImplicitSpec: "v"},
		{CanonicalName: "af", ShortName: "af", Description: "audio filtergraph", Scope: ScopePerStreamOpt, Type: TypeValue, ValueType: ValueFilter, ImplicitSpec: "a"},
		{CanonicalName: "i", ShortName: "i", Description: "input file", Scope: ScopeInputOnlyOpt, Type: TypeValue, ValueType: ValueFileURL},

		// Advanced options (ffplay-specific)
		{CanonicalName: "stats", ShortName: "stats", Description: "print playback statistics", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "fast", ShortName: "fast", Description: "non-spec-compliant optimizations", Scope: ScopePerFileOpt, Type: TypeBoolean},
		{CanonicalName: "genpts", ShortName: "genpts", Description: "generate PTS", Scope: ScopePerFileOpt, Type: TypeBoolean},
		{CanonicalName: "sync", ShortName: "sync", Description: "master clock: audio, video, ext", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueSyncType},
		{CanonicalName: "ast", ShortName: "ast", Description: "select audio stream by specifier", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueStreamSpec},
		{CanonicalName: "vst", ShortName: "vst", Description: "select video stream by specifier", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueStreamSpec},
		{CanonicalName: "sst", ShortName: "sst", Description: "select subtitle stream by specifier", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueStreamSpec},
		{CanonicalName: "autoexit", ShortName: "autoexit", Description: "exit when playback finishes", Scope: ScopePerFileOpt, Type: TypeBoolean},
		{CanonicalName: "exitonkeydown", ShortName: "exitonkeydown", Description: "exit on any key press", Scope: ScopePerFileOpt, Type: TypeBoolean},
		{CanonicalName: "exitonmousedown", ShortName: "exitonmousedown", Description: "exit on any mouse click", Scope: ScopePerFileOpt, Type: TypeBoolean},
		{CanonicalName: "codec", ShortName: "c", Aliases: []string{"acodec", "vcodec", "scodec"}, Description: "force decoder by media specifier", Scope: ScopePerStreamOpt, Type: TypeValue, ValueType: ValueCodec, AcceptsSpec: true},
		{CanonicalName: "autorotate", ShortName: "autorotate", Description: "auto-rotate video by metadata", Scope: ScopePerStreamOpt, Type: TypeBoolean, AcceptsSpec: true},
		{CanonicalName: "framedrop", ShortName: "framedrop", Description: "drop video frames when out of sync", Scope: ScopePerFileOpt, Type: TypeBoolean},
		{CanonicalName: "infbuf", ShortName: "infbuf", Description: "don't limit input buffer size", Scope: ScopePerFileOpt, Type: TypeBoolean},
		{CanonicalName: "filter_threads", ShortName: "filter_threads", Description: "threads for filter pipeline (0=auto)", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueInt},
		{CanonicalName: "enable_vulkan", ShortName: "enable_vulkan", Description: "use Vulkan renderer", Scope: ScopePerFileOpt, Type: TypeBoolean},
		{CanonicalName: "vulkan_params", ShortName: "vulkan_params", Description: "Vulkan configuration (key:value pairs)", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueVulkanParams},
		{CanonicalName: "hwaccel", ShortName: "hwaccel", Description: "use HW accelerated decoding", Scope: ScopePerFileOpt, Type: TypeBoolean},
		{CanonicalName: "video_bg", ShortName: "video_bg", Description: "video background: color, tiles, none", Scope: ScopePerFileOpt, Type: TypeValue, ValueType: ValueString},
	}

	return buildIndexFromOptions(options)
}
