package argstream

// buildFFprobeOptionIndex returns the option index for ffprobe.
func buildFFprobeOptionIndex() map[string]*OptionDef {
	options := []*OptionDef{
		// Global options (shared with ffmpeg)
		{CanonicalName: "L", ShortName: "L", Aliases: []string{"license"}, Description: "show license", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "h", ShortName: "h", Aliases: []string{"help", "?"}, Description: "show help", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueString},
		{CanonicalName: "version", ShortName: "version", Description: "show version", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "buildconf", ShortName: "buildconf", Description: "show build configuration", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "formats", ShortName: "formats", Description: "show available formats", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "demuxers", ShortName: "demuxers", Description: "show available demuxers", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "muxers", ShortName: "muxers", Description: "show available muxers", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "devices", ShortName: "devices", Description: "show available devices", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "codecs", ShortName: "codecs", Description: "show available codecs", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "decoders", ShortName: "decoders", Description: "show available decoders", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "encoders", ShortName: "encoders", Description: "show available encoders", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "bsfs", ShortName: "bsfs", Description: "show available bitstream filters", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "protocols", ShortName: "protocols", Description: "show available protocols", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "filters", ShortName: "filters", Description: "show available filters", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "pix_fmts", ShortName: "pix_fmts", Description: "show available pixel formats", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "sample_fmts", ShortName: "sample_fmts", Description: "show available sample formats", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "layouts", ShortName: "layouts", Description: "show channel layouts", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "dispositions", ShortName: "dispositions", Description: "show stream dispositions", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "colors", ShortName: "colors", Description: "show recognized color names", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "sources", ShortName: "sources", Description: "list sources of the input device", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueDevice},
		{CanonicalName: "sinks", ShortName: "sinks", Description: "list sinks of the output device", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueDevice},
		{CanonicalName: "loglevel", ShortName: "v", Description: "set logging level", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueLogLevel},
		{CanonicalName: "report", ShortName: "report", Description: "generate a report", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "hide_banner", ShortName: "hide_banner", Description: "suppress startup banner", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueBoolean},
		{CanonicalName: "cpuflags", ShortName: "cpuflags", Description: "force specific CPU flags", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueString},
		{CanonicalName: "cpucount", ShortName: "cpucount", Description: "force specific CPU count", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueInt},
		{CanonicalName: "max_alloc", ShortName: "max_alloc", Description: "set maximum memory allocation", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueInt},

		// Main options (ffprobe-specific)
		{CanonicalName: "f", ShortName: "f", Description: "force format", Scope: ScopeInputOnlyOpt, Type: TypeValue, ValueType: ValueFormat},
		{CanonicalName: "unit", ShortName: "unit", Description: "show unit of displayed values", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "prefix", ShortName: "prefix", Description: "use SI prefixes for values", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "byte_binary_prefix", ShortName: "byte_binary_prefix", Description: "force binary prefixes for bytes", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "sexagesimal", ShortName: "sexagesimal", Description: "use HH:MM:SS.MICROSECONDS format", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "pretty", ShortName: "pretty", Description: "shorthand for -unit -prefix -byte_binary_prefix -sexagesimal", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "output_format", ShortName: "of", Aliases: []string{"print_format"}, Description: "output printing format", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueProbeOutputFmt},
		{CanonicalName: "sections", ShortName: "sections", Description: "print section structure and exit", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "select_streams", ShortName: "select_streams", Description: "select streams by specifier", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueStreamSpec},
		{CanonicalName: "show_data", ShortName: "show_data", Description: "show payload data as hex+ASCII", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "show_data_hash", ShortName: "show_data_hash", Description: "hash algorithm for payload data", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueString},
		{CanonicalName: "data_dump_format", ShortName: "data_dump_format", Description: "format for -show_data: xxd, base64", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueDataDumpFmt},
		{CanonicalName: "show_error", ShortName: "show_error", Description: "show probe error info", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "show_format", ShortName: "show_format", Description: "show container format info", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "show_entries", ShortName: "show_entries", Description: "set entries to show", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueString},
		{CanonicalName: "show_packets", ShortName: "show_packets", Description: "show packet info", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "show_frames", ShortName: "show_frames", Description: "show frame and subtitle info", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "show_log", ShortName: "show_log", Description: "show decoder log per frame", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueLogLevel},
		{CanonicalName: "show_streams", ShortName: "show_streams", Description: "show stream info", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "show_programs", ShortName: "show_programs", Description: "show program info", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "show_stream_groups", ShortName: "show_stream_groups", Description: "show stream group info", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "show_chapters", ShortName: "show_chapters", Description: "show chapter info", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "count_frames", ShortName: "count_frames", Description: "count frames per stream", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "count_packets", ShortName: "count_packets", Description: "count packets per stream", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "read_intervals", ShortName: "read_intervals", Description: "read only specified intervals", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueString},
		{CanonicalName: "show_private_data", ShortName: "private", Description: "show private data", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "show_program_version", ShortName: "show_program_version", Description: "show program version", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "show_library_versions", ShortName: "show_library_versions", Description: "show library versions", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "show_versions", ShortName: "show_versions", Description: "show program and library versions", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "show_pixel_formats", ShortName: "show_pixel_formats", Description: "show pixel format info", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "show_optional_fields", ShortName: "show_optional_fields", Description: "print invalid fields: always/1, never/0, auto/-1", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueShowOptFields},
		{CanonicalName: "analyze_frames", ShortName: "analyze_frames", Description: "analyze frames for additional stream info", Scope: ScopeGlobalOpt, Type: TypeBoolean},
		{CanonicalName: "bitexact", ShortName: "bitexact", Description: "force bitexact output", Scope: ScopePerFileOpt, Type: TypeBoolean},
		{CanonicalName: "i", ShortName: "i", Description: "input file", Scope: ScopeInputOnlyOpt, Type: TypeValue, ValueType: ValueFileURL},
		{CanonicalName: "o", ShortName: "o", Description: "write output to file", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueFileURL},
		{CanonicalName: "print_filename", ShortName: "print_filename", Description: "override the printed input filename", Scope: ScopeGlobalOpt, Type: TypeValue, ValueType: ValueString},
		{CanonicalName: "find_stream_info", ShortName: "find_stream_info", Description: "read and decode the streams to fill missing information with heuristics", Scope: ScopeInputOnlyOpt, Type: TypeBoolean},
		{CanonicalName: "codec", ShortName: "c", Aliases: []string{"acodec", "vcodec", "scodec"}, Description: "force decoder by media specifier", Scope: ScopePerStreamOpt, Type: TypeValue, ValueType: ValueCodec, AcceptsSpec: true},
	}

	return buildIndexFromOptions(options)
}
